### ISSUE TITLE
请求参数支持json类型

### ISSUE THREAD

**Issue by znau** [EhsanTang/CrapApi#21]
对于Restful 风格api ，参数可能会传送一段json字符，例如：
        `data={"did":"sssfsdfsdf","mfrom":"eced"}`   
这个可以参考 小幺鸡(http://www.xiaoyaoji.com.cn/) 里 请求参数类型有一个object类型。希望CrapApi以后可以支持。

另：1. 小幺鸡 右上角有一个环境的选择，感觉也挺实用的
       2.  如果能够根据接口生成一段curl 命令就更好了 
        `curl -k -L -X  POST  "http://api.xxxx.cn/abc/def"  -d data='{"did":"sssfsdfsdf","mfrom":"eced"}'`

**Comment by EhsanTang** [comment]
目前支持参数中传json数据，详情见样例：http://api.crap.cn/index.do#/de2055f4-656a-495b-85dd-6591922bdf5d/front/interfaceDetail/895aaabc-f3d7-461c-bad6-e9c44f6cdb4f  ，选择自定义参数即可输入json，并且支持为json串添加备注

环境切换、curl会考虑加上
