### ISSUE TITLE
新建角色显示乱码

### ISSUE THREAD

**Issue by liuqi0622** [EhsanTang/CrapApi#5]
服务端收到中文显示乱码。我在controller打印出接收内容，显示乱码。

另外，BaseController中log为私有，建议改为保护，否则子类无法使用。

**Comment by EhsanTang** [comment]
BaseController中log为私有，建议改为保护，否则子类无法使用 —— 已采纳
服务端收到中文显示乱码——无法复现：系统采用的是UTF-8，请确认你的项目编码，网络请求传递时中文是否乱码

**Comment by EhsanTang** [comment]
注意数据库是否使用utf-8编码，更多详情见：http://api.crap.cn/web.do#/webWebPage/detail/ARTICLE/f0229c53-1580-4b74-be0c-365b1fd4966d
